import { createHmac } from 'crypto';
import {
  PopupStateStore,
  isPopupState,
} from '@authentication/infrastructure/helpers/popup-state-store';

// ── Helpers ──────────────────────────────────────────────────────────────────

function makeReq(mode?: string): { query: Record<string, string> } {
  return { query: mode ? { mode } : {} };
}

// ─────────────────────────────────────────────────────────────────────────────
// PopupStateStore
// ─────────────────────────────────────────────────────────────────────────────

describe('PopupStateStore', () => {
  const SECRET = 'test-secret-must-be-at-least-32-chars!!';
  let store: PopupStateStore;

  beforeEach(() => {
    store = new PopupStateStore(SECRET);
  });

  // ── store() ────────────────────────────────────────────────────────────────

  describe('Given the request has mode=popup', () => {
    describe('When store() is called', () => {
      it('Then the state starts with "popup:" and matches the signed format', (done) => {
        store.store(makeReq('popup') as never, (err, state) => {
          expect(err).toBeNull();
          expect(state).toMatch(/^popup:[a-f0-9]+:\d+\.[a-f0-9]+$/);
          done();
        });
      });
    });
  });

  describe('Given the request has no mode', () => {
    describe('When store() is called', () => {
      it('Then the state does not start with "popup:" and matches the signed format', (done) => {
        store.store(makeReq() as never, (err, state) => {
          expect(err).toBeNull();
          expect(state).not.toMatch(/^popup:/);
          expect(state).toMatch(/^[a-f0-9]+:\d+\.[a-f0-9]+$/);
          done();
        });
      });
    });
  });

  // ── verify() ───────────────────────────────────────────────────────────────

  describe('Given a valid popup state generated by store()', () => {
    describe('When verify() is called', () => {
      it('Then ok is true', (done) => {
        store.store(makeReq('popup') as never, (_err, state) => {
          store.verify({} as never, state, (err, ok) => {
            expect(err).toBeNull();
            expect(ok).toBe(true);
            done();
          });
        });
      });
    });
  });

  describe('Given a valid normal state generated by store()', () => {
    describe('When verify() is called', () => {
      it('Then ok is true', (done) => {
        store.store(makeReq() as never, (_err, state) => {
          store.verify({} as never, state, (err, ok) => {
            expect(err).toBeNull();
            expect(ok).toBe(true);
            done();
          });
        });
      });
    });
  });

  describe('Given a state with no dot separator (no signature)', () => {
    describe('When verify() is called', () => {
      it('Then ok is false', (done) => {
        store.verify({} as never, 'popup:abc123:1234567890', (err, ok) => {
          expect(err).toBeNull();
          expect(ok).toBe(false);
          done();
        });
      });
    });
  });

  describe('Given a state with a tampered signature', () => {
    describe('When verify() is called', () => {
      it('Then ok is false', (done) => {
        store.store(makeReq() as never, (_err, state) => {
          // Replace last character of the hex signature to tamper it
          const lastChar = state[state.length - 1];
          const replacement = lastChar === 'a' ? 'b' : 'a';
          const tampered = state.slice(0, -1) + replacement;
          store.verify({} as never, tampered, (err, ok) => {
            expect(err).toBeNull();
            expect(ok).toBe(false);
            done();
          });
        });
      });
    });
  });

  describe('Given a state signed with a different secret', () => {
    describe('When verify() is called', () => {
      it('Then ok is false', (done) => {
        const otherStore = new PopupStateStore('different-secret-32-chars-minimum!!');
        otherStore.store(makeReq() as never, (_err, state) => {
          store.verify({} as never, state, (err, ok) => {
            expect(err).toBeNull();
            expect(ok).toBe(false);
            done();
          });
        });
      });
    });
  });

  describe('Given a state with an expired timestamp (older than 10 minutes)', () => {
    describe('When verify() is called', () => {
      it('Then ok is false', (done) => {
        const expiredTs = (Date.now() - 11 * 60 * 1000).toString();
        const nonce = 'aabbccddeeff00112233445566778899';
        const payload = `${nonce}:${expiredTs}`;
        const sig = createHmac('sha256', SECRET).update(payload).digest('hex');
        const state = `${payload}.${sig}`;
        store.verify({} as never, state, (err, ok) => {
          expect(err).toBeNull();
          expect(ok).toBe(false);
          done();
        });
      });
    });
  });

  describe('Given a state with a non-hex signature (invalid encoding)', () => {
    describe('When verify() is called', () => {
      it('Then ok is false', (done) => {
        store.verify({} as never, 'abc:12345.not-valid-hex!!!!', (err, ok) => {
          expect(err).toBeNull();
          expect(ok).toBe(false);
          done();
        });
      });
    });
  });

  describe('Given a state payload with a non-numeric timestamp', () => {
    describe('When verify() is called', () => {
      it('Then ok is false', (done) => {
        const payload = 'aabbccdd:not-a-number';
        const sig = createHmac('sha256', SECRET).update(payload).digest('hex');
        store.verify({} as never, `${payload}.${sig}`, (err, ok) => {
          expect(err).toBeNull();
          expect(ok).toBe(false);
          done();
        });
      });
    });
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// isPopupState
// ─────────────────────────────────────────────────────────────────────────────

describe('isPopupState', () => {
  describe('Given a state string that starts with "popup:"', () => {
    it('Then it returns true', () => {
      expect(isPopupState('popup:abc:123.sig')).toBe(true);
    });
  });

  describe('Given a state string that does not start with "popup:"', () => {
    it('Then it returns false', () => {
      expect(isPopupState('abc:123.sig')).toBe(false);
    });
  });

  describe('Given undefined', () => {
    it('Then it returns false', () => {
      expect(isPopupState(undefined)).toBe(false);
    });
  });
});
