export enum StorageActivityAction {
  CREATED = 'CREATED',
  NAME_CHANGED = 'NAME_CHANGED',
  TYPE_CHANGED = 'TYPE_CHANGED',
  DESCRIPTION_CHANGED = 'DESCRIPTION_CHANGED',
  ADDRESS_CHANGED = 'ADDRESS_CHANGED',
  ICON_CHANGED = 'ICON_CHANGED',
  COLOR_CHANGED = 'COLOR_CHANGED',
  FROZEN = 'FROZEN',
  REACTIVATED = 'REACTIVATED',
  ARCHIVED = 'ARCHIVED',
  RESTORED = 'RESTORED',
}
