export const APP_CONSTANTS = {
  API_PREFIX: 'api',
  DEFAULT_PORT: 3001,
  BCRYPT_SALT_ROUNDS: parseInt(process.env.BCRYPT_ROUNDS ?? '12', 10),
  DEFAULT_TIMEOUT_MS: 10000,
} as const;

export const INJECTION_TOKENS = {
  USER_CONTRACT: 'USER_CONTRACT',
  USER_FACADE: 'USER_FACADE',
  SESSION_CONTRACT: 'SESSION_CONTRACT',
  PASSWORD_RESET_TOKEN_CONTRACT: 'PASSWORD_RESET_TOKEN_CONTRACT',
  EMAIL_VERIFICATION_TOKEN_CONTRACT: 'EMAIL_VERIFICATION_TOKEN_CONTRACT',
  VERIFICATION_ATTEMPT_CONTRACT: 'VERIFICATION_ATTEMPT_CONTRACT',
  EMAIL_PROVIDER_CONTRACT: 'EMAIL_PROVIDER_CONTRACT',
  CODE_GENERATOR_CONTRACT: 'CODE_GENERATOR_CONTRACT',
  SOCIAL_ACCOUNT_CONTRACT: 'SOCIAL_ACCOUNT_CONTRACT',
  PROCESS_STATE_CONTRACT: 'PROCESS_STATE_CONTRACT',
  UNIT_OF_WORK: 'UNIT_OF_WORK',
} as const;
