export const APP_CONSTANTS = {
  API_PREFIX: 'api',
  DEFAULT_PORT: 3001,
  BCRYPT_SALT_ROUNDS: 12,
  DEFAULT_TIMEOUT_MS: 10000,
} as const;

export const INJECTION_TOKENS = {
  USER_CONTRACT: 'USER_CONTRACT',
  USER_FACADE: 'USER_FACADE',
  SESSION_CONTRACT: 'SESSION_CONTRACT',
  PASSWORD_RESET_TOKEN_CONTRACT: 'PASSWORD_RESET_TOKEN_CONTRACT',
  EMAIL_VERIFICATION_TOKEN_CONTRACT: 'EMAIL_VERIFICATION_TOKEN_CONTRACT',
  VERIFICATION_ATTEMPT_CONTRACT: 'VERIFICATION_ATTEMPT_CONTRACT',
  EMAIL_PROVIDER_CONTRACT: 'EMAIL_PROVIDER_CONTRACT',
  CODE_GENERATOR_CONTRACT: 'CODE_GENERATOR_CONTRACT',
} as const;
