type Country = {
  code: string; // ISO 3166-1 alpha-2,
  alpha3: string; // ISO 3166-1 alpha-3
  number: string; // ISO numeric
  name: string; // Common English name
  i18n: {
    en: string; // English name
    es: string; // Spanish name
  };
  region: 'Africa' | 'Americas' | 'Asia' | 'Europe' | 'Oceania'; // Geographical region
  phoneCode: string; // International phone code
  currency: string; // ISO 4217 currency code
  locale: string; // Default locale (e.g., en-US)
  flagEmoji: string; // Unicode emoji of the flag
};

export const COUNTRY_MASTER_DATA: Country[] = [
  {
    code: 'AF',
    alpha3: 'AFG',
    number: '004',
    name: 'Afghanistan',
    i18n: {
      en: 'Afghanistan',
      es: 'Afganistán',
    },
    region: 'Asia',
    phoneCode: '93',
    currency: 'AFN',
    locale: 'prs-AF',
    flagEmoji: '🇦🇫',
  },
  {
    code: 'AX',
    alpha3: 'ALA',
    number: '248',
    name: 'Åland Islands',
    i18n: {
      en: 'Åland Islands',
      es: 'Alandia',
    },
    region: 'Europe',
    phoneCode: '35818',
    currency: 'EUR',
    locale: 'swe-AX',
    flagEmoji: '🇦🇽',
  },
  {
    code: 'AL',
    alpha3: 'ALB',
    number: '008',
    name: 'Albania',
    i18n: {
      en: 'Albania',
      es: 'Albania',
    },
    region: 'Europe',
    phoneCode: '355',
    currency: 'ALL',
    locale: 'sqi-AL',
    flagEmoji: '🇦🇱',
  },
  {
    code: 'DZ',
    alpha3: 'DZA',
    number: '012',
    name: 'Algeria',
    i18n: {
      en: 'Algeria',
      es: 'Argelia',
    },
    region: 'Africa',
    phoneCode: '213',
    currency: 'DZD',
    locale: 'ara-DZ',
    flagEmoji: '🇩🇿',
  },
  {
    code: 'AS',
    alpha3: 'ASM',
    number: '016',
    name: 'American Samoa',
    i18n: {
      en: 'American Samoa',
      es: 'Samoa Americana',
    },
    region: 'Oceania',
    phoneCode: '1684',
    currency: 'USD',
    locale: 'eng-AS',
    flagEmoji: '🇦🇸',
  },
  {
    code: 'AD',
    alpha3: 'AND',
    number: '020',
    name: 'Andorra',
    i18n: {
      en: 'Andorra',
      es: 'Andorra',
    },
    region: 'Europe',
    phoneCode: '376',
    currency: 'EUR',
    locale: 'cat-AD',
    flagEmoji: '🇦🇩',
  },
  {
    code: 'AO',
    alpha3: 'AGO',
    number: '024',
    name: 'Angola',
    i18n: {
      en: 'Angola',
      es: 'Angola',
    },
    region: 'Africa',
    phoneCode: '244',
    currency: 'AOA',
    locale: 'por-AO',
    flagEmoji: '🇦🇴',
  },
  {
    code: 'AI',
    alpha3: 'AIA',
    number: '660',
    name: 'Anguilla',
    i18n: {
      en: 'Anguilla',
      es: 'Anguilla',
    },
    region: 'Americas',
    phoneCode: '1264',
    currency: 'XCD',
    locale: 'eng-AI',
    flagEmoji: '🇦🇮',
  },
  {
    code: 'AQ',
    alpha3: 'ATA',
    number: '010',
    name: 'Antarctica',
    i18n: {
      en: 'Antarctica',
      es: 'Antártida',
    },
    region: 'Oceania',
    phoneCode: '',
    locale: 'undefined-AQ',
    currency: '',
    flagEmoji: '🇦🇶',
  },
  {
    code: 'AG',
    alpha3: 'ATG',
    number: '028',
    name: 'Antigua and Barbuda',
    i18n: {
      en: 'Antigua and Barbuda',
      es: 'Antigua y Barbuda',
    },
    region: 'Americas',
    phoneCode: '1268',
    currency: 'XCD',
    locale: 'eng-AG',
    flagEmoji: '🇦🇬',
  },
  {
    code: 'AR',
    alpha3: 'ARG',
    number: '032',
    name: 'Argentina',
    i18n: {
      en: 'Argentina',
      es: 'Argentina',
    },
    region: 'Americas',
    phoneCode: '54',
    currency: 'ARS',
    locale: 'grn-AR',
    flagEmoji: '🇦🇷',
  },
  {
    code: 'AM',
    alpha3: 'ARM',
    number: '051',
    name: 'Armenia',
    i18n: {
      en: 'Armenia',
      es: 'Armenia',
    },
    region: 'Asia',
    phoneCode: '374',
    currency: 'AMD',
    locale: 'hye-AM',
    flagEmoji: '🇦🇲',
  },
  {
    code: 'AW',
    alpha3: 'ABW',
    number: '533',
    name: 'Aruba',
    i18n: {
      en: 'Aruba',
      es: 'Aruba',
    },
    region: 'Americas',
    phoneCode: '297',
    currency: 'AWG',
    locale: 'nld-AW',
    flagEmoji: '🇦🇼',
  },
  {
    code: 'AU',
    alpha3: 'AUS',
    number: '036',
    name: 'Australia',
    i18n: {
      en: 'Australia',
      es: 'Australia',
    },
    region: 'Oceania',
    phoneCode: '61',
    currency: 'AUD',
    locale: 'eng-AU',
    flagEmoji: '🇦🇺',
  },
  {
    code: 'AT',
    alpha3: 'AUT',
    number: '040',
    name: 'Austria',
    i18n: {
      en: 'Austria',
      es: 'Austria',
    },
    region: 'Europe',
    phoneCode: '43',
    currency: 'EUR',
    locale: 'deu-AT',
    flagEmoji: '🇦🇹',
  },
  {
    code: 'AZ',
    alpha3: 'AZE',
    number: '031',
    name: 'Azerbaijan',
    i18n: {
      en: 'Azerbaijan',
      es: 'Azerbaiyán',
    },
    region: 'Asia',
    phoneCode: '994',
    currency: 'AZN',
    locale: 'aze-AZ',
    flagEmoji: '🇦🇿',
  },
  {
    code: 'BS',
    alpha3: 'BHS',
    number: '044',
    name: 'Bahamas',
    i18n: {
      en: 'Bahamas',
      es: 'Bahamas',
    },
    region: 'Americas',
    phoneCode: '1242',
    currency: 'BSD',
    locale: 'eng-BS',
    flagEmoji: '🇧🇸',
  },
  {
    code: 'BH',
    alpha3: 'BHR',
    number: '048',
    name: 'Bahrain',
    i18n: {
      en: 'Bahrain',
      es: 'Bahrein',
    },
    region: 'Asia',
    phoneCode: '973',
    currency: 'BHD',
    locale: 'ara-BH',
    flagEmoji: '🇧🇭',
  },
  {
    code: 'BD',
    alpha3: 'BGD',
    number: '050',
    name: 'Bangladesh',
    i18n: {
      en: 'Bangladesh',
      es: 'Bangladesh',
    },
    region: 'Asia',
    phoneCode: '880',
    currency: 'BDT',
    locale: 'ben-BD',
    flagEmoji: '🇧🇩',
  },
  {
    code: 'BB',
    alpha3: 'BRB',
    number: '052',
    name: 'Barbados',
    i18n: {
      en: 'Barbados',
      es: 'Barbados',
    },
    region: 'Americas',
    phoneCode: '1246',
    currency: 'BBD',
    locale: 'eng-BB',
    flagEmoji: '🇧🇧',
  },
  {
    code: 'BY',
    alpha3: 'BLR',
    number: '112',
    name: 'Belarus',
    i18n: {
      en: 'Belarus',
      es: 'Bielorrusia',
    },
    region: 'Europe',
    phoneCode: '375',
    currency: 'BYN',
    locale: 'bel-BY',
    flagEmoji: '🇧🇾',
  },
  {
    code: 'BE',
    alpha3: 'BEL',
    number: '056',
    name: 'Belgium',
    i18n: {
      en: 'Belgium',
      es: 'Bélgica',
    },
    region: 'Europe',
    phoneCode: '32',
    currency: 'EUR',
    locale: 'deu-BE',
    flagEmoji: '🇧🇪',
  },
  {
    code: 'BZ',
    alpha3: 'BLZ',
    number: '084',
    name: 'Belize',
    i18n: {
      en: 'Belize',
      es: 'Belice',
    },
    region: 'Americas',
    phoneCode: '501',
    currency: 'BZD',
    locale: 'bjz-BZ',
    flagEmoji: '🇧🇿',
  },
  {
    code: 'BJ',
    alpha3: 'BEN',
    number: '204',
    name: 'Benin',
    i18n: {
      en: 'Benin',
      es: 'Benín',
    },
    region: 'Africa',
    phoneCode: '229',
    currency: 'XOF',
    locale: 'fra-BJ',
    flagEmoji: '🇧🇯',
  },
  {
    code: 'BM',
    alpha3: 'BMU',
    number: '060',
    name: 'Bermuda',
    i18n: {
      en: 'Bermuda',
      es: 'Bermudas',
    },
    region: 'Americas',
    phoneCode: '1441',
    currency: 'BMD',
    locale: 'eng-BM',
    flagEmoji: '🇧🇲',
  },
  {
    code: 'BT',
    alpha3: 'BTN',
    number: '064',
    name: 'Bhutan',
    i18n: {
      en: 'Bhutan',
      es: 'Bután',
    },
    region: 'Asia',
    phoneCode: '975',
    currency: 'BTN',
    locale: 'dzo-BT',
    flagEmoji: '🇧🇹',
  },
  {
    code: 'BO',
    alpha3: 'BOL',
    number: '068',
    name: 'Bolivia',
    i18n: {
      en: 'Bolivia',
      es: 'Bolivia',
    },
    region: 'Americas',
    phoneCode: '591',
    currency: 'BOB',
    locale: 'aym-BO',
    flagEmoji: '🇧🇴',
  },
  {
    code: 'BA',
    alpha3: 'BIH',
    number: '070',
    name: 'Bosnia and Herzegovina',
    i18n: {
      en: 'Bosnia and Herzegovina',
      es: 'Bosnia y Herzegovina',
    },
    region: 'Europe',
    phoneCode: '387',
    currency: 'BAM',
    locale: 'bos-BA',
    flagEmoji: '🇧🇦',
  },
  {
    code: 'BW',
    alpha3: 'BWA',
    number: '072',
    name: 'Botswana',
    i18n: {
      en: 'Botswana',
      es: 'Botswana',
    },
    region: 'Africa',
    phoneCode: '267',
    currency: 'BWP',
    locale: 'eng-BW',
    flagEmoji: '🇧🇼',
  },
  {
    code: 'BV',
    alpha3: 'BVT',
    number: '074',
    name: 'Bouvet Island',
    i18n: {
      en: 'Bouvet Island',
      es: 'Isla Bouvet',
    },
    region: 'Oceania',
    phoneCode: '47',
    currency: 'NOK',
    locale: 'nor-BV',
    flagEmoji: '🇧🇻',
  },
  {
    code: 'BR',
    alpha3: 'BRA',
    number: '076',
    name: 'Brazil',
    i18n: {
      en: 'Brazil',
      es: 'Brasil',
    },
    region: 'Americas',
    phoneCode: '55',
    currency: 'BRL',
    locale: 'por-BR',
    flagEmoji: '🇧🇷',
  },
  {
    code: 'IO',
    alpha3: 'IOT',
    number: '086',
    name: 'British Indian Ocean Territory',
    i18n: {
      en: 'British Indian Ocean Territory',
      es: 'Territorio Británico del Océano Índico',
    },
    region: 'Africa',
    phoneCode: '246',
    currency: 'USD',
    locale: 'eng-IO',
    flagEmoji: '🇮🇴',
  },
  {
    code: 'VG',
    alpha3: 'VGB',
    number: '092',
    name: 'British Virgin Islands',
    i18n: {
      en: 'British Virgin Islands',
      es: 'Islas Vírgenes del Reino Unido',
    },
    region: 'Americas',
    phoneCode: '1284',
    currency: 'USD',
    locale: 'eng-VG',
    flagEmoji: '🇻🇬',
  },
  {
    code: 'BN',
    alpha3: 'BRN',
    number: '096',
    name: 'Brunei',
    i18n: {
      en: 'Brunei',
      es: 'Brunei',
    },
    region: 'Asia',
    phoneCode: '673',
    currency: 'BND',
    locale: 'msa-BN',
    flagEmoji: '🇧🇳',
  },
  {
    code: 'BG',
    alpha3: 'BGR',
    number: '100',
    name: 'Bulgaria',
    i18n: {
      en: 'Bulgaria',
      es: 'Bulgaria',
    },
    region: 'Europe',
    phoneCode: '359',
    currency: 'BGN',
    locale: 'bul-BG',
    flagEmoji: '🇧🇬',
  },
  {
    code: 'BF',
    alpha3: 'BFA',
    number: '854',
    name: 'Burkina Faso',
    i18n: {
      en: 'Burkina Faso',
      es: 'Burkina Faso',
    },
    region: 'Africa',
    phoneCode: '226',
    currency: 'XOF',
    locale: 'fra-BF',
    flagEmoji: '🇧🇫',
  },
  {
    code: 'BI',
    alpha3: 'BDI',
    number: '108',
    name: 'Burundi',
    i18n: {
      en: 'Burundi',
      es: 'Burundi',
    },
    region: 'Africa',
    phoneCode: '257',
    currency: 'BIF',
    locale: 'fra-BI',
    flagEmoji: '🇧🇮',
  },
  {
    code: 'KH',
    alpha3: 'KHM',
    number: '116',
    name: 'Cambodia',
    i18n: {
      en: 'Cambodia',
      es: 'Camboya',
    },
    region: 'Asia',
    phoneCode: '855',
    currency: 'KHR',
    locale: 'khm-KH',
    flagEmoji: '🇰🇭',
  },
  {
    code: 'CM',
    alpha3: 'CMR',
    number: '120',
    name: 'Cameroon',
    i18n: {
      en: 'Cameroon',
      es: 'Camerún',
    },
    region: 'Africa',
    phoneCode: '237',
    currency: 'XAF',
    locale: 'eng-CM',
    flagEmoji: '🇨🇲',
  },
  {
    code: 'CA',
    alpha3: 'CAN',
    number: '124',
    name: 'Canada',
    i18n: {
      en: 'Canada',
      es: 'Canadá',
    },
    region: 'Americas',
    phoneCode: '1',
    currency: 'CAD',
    locale: 'eng-CA',
    flagEmoji: '🇨🇦',
  },
  {
    code: 'CV',
    alpha3: 'CPV',
    number: '132',
    name: 'Cape Verde',
    i18n: {
      en: 'Cape Verde',
      es: 'Cabo Verde',
    },
    region: 'Africa',
    phoneCode: '238',
    currency: 'CVE',
    locale: 'por-CV',
    flagEmoji: '🇨🇻',
  },
  {
    code: 'BQ',
    alpha3: 'BES',
    number: '535',
    name: 'Caribbean Netherlands',
    i18n: {
      en: 'Caribbean Netherlands',
      es: 'Caribe Neerlandés',
    },
    region: 'Americas',
    phoneCode: '599',
    currency: 'USD',
    locale: 'eng-BQ',
    flagEmoji: '🇧🇶',
  },
  {
    code: 'KY',
    alpha3: 'CYM',
    number: '136',
    name: 'Cayman Islands',
    i18n: {
      en: 'Cayman Islands',
      es: 'Islas Caimán',
    },
    region: 'Americas',
    phoneCode: '1345',
    currency: 'KYD',
    locale: 'eng-KY',
    flagEmoji: '🇰🇾',
  },
  {
    code: 'CF',
    alpha3: 'CAF',
    number: '140',
    name: 'Central African Republic',
    i18n: {
      en: 'Central African Republic',
      es: 'República Centroafricana',
    },
    region: 'Africa',
    phoneCode: '236',
    currency: 'XAF',
    locale: 'fra-CF',
    flagEmoji: '🇨🇫',
  },
  {
    code: 'TD',
    alpha3: 'TCD',
    number: '148',
    name: 'Chad',
    i18n: {
      en: 'Chad',
      es: 'Chad',
    },
    region: 'Africa',
    phoneCode: '235',
    currency: 'XAF',
    locale: 'ara-TD',
    flagEmoji: '🇹🇩',
  },
  {
    code: 'CL',
    alpha3: 'CHL',
    number: '152',
    name: 'Chile',
    i18n: {
      en: 'Chile',
      es: 'Chile',
    },
    region: 'Americas',
    phoneCode: '56',
    currency: 'CLP',
    locale: 'spa-CL',
    flagEmoji: '🇨🇱',
  },
  {
    code: 'CN',
    alpha3: 'CHN',
    number: '156',
    name: 'China',
    i18n: {
      en: 'China',
      es: 'China',
    },
    region: 'Asia',
    phoneCode: '86',
    currency: 'CNY',
    locale: 'zho-CN',
    flagEmoji: '🇨🇳',
  },
  {
    code: 'CX',
    alpha3: 'CXR',
    number: '162',
    name: 'Christmas Island',
    i18n: {
      en: 'Christmas Island',
      es: 'Isla de Navidad',
    },
    region: 'Oceania',
    phoneCode: '61',
    currency: 'AUD',
    locale: 'eng-CX',
    flagEmoji: '🇨🇽',
  },
  {
    code: 'CC',
    alpha3: 'CCK',
    number: '166',
    name: 'Cocos (Keeling) Islands',
    i18n: {
      en: 'Cocos (Keeling) Islands',
      es: 'Islas Cocos o Islas Keeling',
    },
    region: 'Oceania',
    phoneCode: '61',
    currency: 'AUD',
    locale: 'eng-CC',
    flagEmoji: '🇨🇨',
  },
  {
    code: 'CO',
    alpha3: 'COL',
    number: '170',
    name: 'Colombia',
    i18n: {
      en: 'Colombia',
      es: 'Colombia',
    },
    region: 'Americas',
    phoneCode: '57',
    currency: 'COP',
    locale: 'spa-CO',
    flagEmoji: '🇨🇴',
  },
  {
    code: 'KM',
    alpha3: 'COM',
    number: '174',
    name: 'Comoros',
    i18n: {
      en: 'Comoros',
      es: 'Comoras',
    },
    region: 'Africa',
    phoneCode: '269',
    currency: 'KMF',
    locale: 'ara-KM',
    flagEmoji: '🇰🇲',
  },
  {
    code: 'CK',
    alpha3: 'COK',
    number: '184',
    name: 'Cook Islands',
    i18n: {
      en: 'Cook Islands',
      es: 'Islas Cook',
    },
    region: 'Oceania',
    phoneCode: '682',
    currency: 'CKD',
    locale: 'eng-CK',
    flagEmoji: '🇨🇰',
  },
  {
    code: 'CR',
    alpha3: 'CRI',
    number: '188',
    name: 'Costa Rica',
    i18n: {
      en: 'Costa Rica',
      es: 'Costa Rica',
    },
    region: 'Americas',
    phoneCode: '506',
    currency: 'CRC',
    locale: 'spa-CR',
    flagEmoji: '🇨🇷',
  },
  {
    code: 'HR',
    alpha3: 'HRV',
    number: '191',
    name: 'Croatia',
    i18n: {
      en: 'Croatia',
      es: 'Croacia',
    },
    region: 'Europe',
    phoneCode: '385',
    currency: 'EUR',
    locale: 'hrv-HR',
    flagEmoji: '🇭🇷',
  },
  {
    code: 'CU',
    alpha3: 'CUB',
    number: '192',
    name: 'Cuba',
    i18n: {
      en: 'Cuba',
      es: 'Cuba',
    },
    region: 'Americas',
    phoneCode: '53',
    currency: 'CUC',
    locale: 'spa-CU',
    flagEmoji: '🇨🇺',
  },
  {
    code: 'CW',
    alpha3: 'CUW',
    number: '531',
    name: 'Curaçao',
    i18n: {
      en: 'Curaçao',
      es: 'Curazao',
    },
    region: 'Americas',
    phoneCode: '599',
    currency: 'ANG',
    locale: 'eng-CW',
    flagEmoji: '🇨🇼',
  },
  {
    code: 'CY',
    alpha3: 'CYP',
    number: '196',
    name: 'Cyprus',
    i18n: {
      en: 'Cyprus',
      es: 'Chipre',
    },
    region: 'Europe',
    phoneCode: '357',
    currency: 'EUR',
    locale: 'ell-CY',
    flagEmoji: '🇨🇾',
  },
  {
    code: 'CZ',
    alpha3: 'CZE',
    number: '203',
    name: 'Czechia',
    i18n: {
      en: 'Czechia',
      es: 'Chequia',
    },
    region: 'Europe',
    phoneCode: '420',
    currency: 'CZK',
    locale: 'ces-CZ',
    flagEmoji: '🇨🇿',
  },
  {
    code: 'DK',
    alpha3: 'DNK',
    number: '208',
    name: 'Denmark',
    i18n: {
      en: 'Denmark',
      es: 'Dinamarca',
    },
    region: 'Europe',
    phoneCode: '45',
    currency: 'DKK',
    locale: 'dan-DK',
    flagEmoji: '🇩🇰',
  },
  {
    code: 'DJ',
    alpha3: 'DJI',
    number: '262',
    name: 'Djibouti',
    i18n: {
      en: 'Djibouti',
      es: 'Djibouti',
    },
    region: 'Africa',
    phoneCode: '253',
    currency: 'DJF',
    locale: 'ara-DJ',
    flagEmoji: '🇩🇯',
  },
  {
    code: 'DM',
    alpha3: 'DMA',
    number: '212',
    name: 'Dominica',
    i18n: {
      en: 'Dominica',
      es: 'Dominica',
    },
    region: 'Americas',
    phoneCode: '1767',
    currency: 'XCD',
    locale: 'eng-DM',
    flagEmoji: '🇩🇲',
  },
  {
    code: 'DO',
    alpha3: 'DOM',
    number: '214',
    name: 'Dominican Republic',
    i18n: {
      en: 'Dominican Republic',
      es: 'República Dominicana',
    },
    region: 'Americas',
    phoneCode: '1809',
    currency: 'DOP',
    locale: 'spa-DO',
    flagEmoji: '🇩🇴',
  },
  {
    code: 'CD',
    alpha3: 'COD',
    number: '180',
    name: 'DR Congo',
    i18n: {
      en: 'DR Congo',
      es: 'Congo (Rep. Dem.)',
    },
    region: 'Africa',
    phoneCode: '243',
    currency: 'CDF',
    locale: 'fra-CD',
    flagEmoji: '🇨🇩',
  },
  {
    code: 'EC',
    alpha3: 'ECU',
    number: '218',
    name: 'Ecuador',
    i18n: {
      en: 'Ecuador',
      es: 'Ecuador',
    },
    region: 'Americas',
    phoneCode: '593',
    currency: 'USD',
    locale: 'spa-EC',
    flagEmoji: '🇪🇨',
  },
  {
    code: 'EG',
    alpha3: 'EGY',
    number: '818',
    name: 'Egypt',
    i18n: {
      en: 'Egypt',
      es: 'Egipto',
    },
    region: 'Africa',
    phoneCode: '20',
    currency: 'EGP',
    locale: 'ara-EG',
    flagEmoji: '🇪🇬',
  },
  {
    code: 'SV',
    alpha3: 'SLV',
    number: '222',
    name: 'El Salvador',
    i18n: {
      en: 'El Salvador',
      es: 'El Salvador',
    },
    region: 'Americas',
    phoneCode: '503',
    currency: 'USD',
    locale: 'spa-SV',
    flagEmoji: '🇸🇻',
  },
  {
    code: 'GQ',
    alpha3: 'GNQ',
    number: '226',
    name: 'Equatorial Guinea',
    i18n: {
      en: 'Equatorial Guinea',
      es: 'Guinea Ecuatorial',
    },
    region: 'Africa',
    phoneCode: '240',
    currency: 'XAF',
    locale: 'fra-GQ',
    flagEmoji: '🇬🇶',
  },
  {
    code: 'ER',
    alpha3: 'ERI',
    number: '232',
    name: 'Eritrea',
    i18n: {
      en: 'Eritrea',
      es: 'Eritrea',
    },
    region: 'Africa',
    phoneCode: '291',
    currency: 'ERN',
    locale: 'ara-ER',
    flagEmoji: '🇪🇷',
  },
  {
    code: 'EE',
    alpha3: 'EST',
    number: '233',
    name: 'Estonia',
    i18n: {
      en: 'Estonia',
      es: 'Estonia',
    },
    region: 'Europe',
    phoneCode: '372',
    currency: 'EUR',
    locale: 'est-EE',
    flagEmoji: '🇪🇪',
  },
  {
    code: 'SZ',
    alpha3: 'SWZ',
    number: '748',
    name: 'Eswatini',
    i18n: {
      en: 'Eswatini',
      es: 'Suazilandia',
    },
    region: 'Africa',
    phoneCode: '268',
    currency: 'SZL',
    locale: 'eng-SZ',
    flagEmoji: '🇸🇿',
  },
  {
    code: 'ET',
    alpha3: 'ETH',
    number: '231',
    name: 'Ethiopia',
    i18n: {
      en: 'Ethiopia',
      es: 'Etiopía',
    },
    region: 'Africa',
    phoneCode: '251',
    currency: 'ETB',
    locale: 'amh-ET',
    flagEmoji: '🇪🇹',
  },
  {
    code: 'FK',
    alpha3: 'FLK',
    number: '238',
    name: 'Falkland Islands',
    i18n: {
      en: 'Falkland Islands',
      es: 'Islas Malvinas',
    },
    region: 'Americas',
    phoneCode: '500',
    currency: 'FKP',
    locale: 'eng-FK',
    flagEmoji: '🇫🇰',
  },
  {
    code: 'FO',
    alpha3: 'FRO',
    number: '234',
    name: 'Faroe Islands',
    i18n: {
      en: 'Faroe Islands',
      es: 'Islas Faroe',
    },
    region: 'Europe',
    phoneCode: '298',
    currency: 'DKK',
    locale: 'dan-FO',
    flagEmoji: '🇫🇴',
  },
  {
    code: 'FJ',
    alpha3: 'FJI',
    number: '242',
    name: 'Fiji',
    i18n: {
      en: 'Fiji',
      es: 'Fiyi',
    },
    region: 'Oceania',
    phoneCode: '679',
    currency: 'FJD',
    locale: 'eng-FJ',
    flagEmoji: '🇫🇯',
  },
  {
    code: 'FI',
    alpha3: 'FIN',
    number: '246',
    name: 'Finland',
    i18n: {
      en: 'Finland',
      es: 'Finlandia',
    },
    region: 'Europe',
    phoneCode: '358',
    currency: 'EUR',
    locale: 'fin-FI',
    flagEmoji: '🇫🇮',
  },
  {
    code: 'FR',
    alpha3: 'FRA',
    number: '250',
    name: 'France',
    i18n: {
      en: 'France',
      es: 'Francia',
    },
    region: 'Europe',
    phoneCode: '33',
    currency: 'EUR',
    locale: 'fra-FR',
    flagEmoji: '🇫🇷',
  },
  {
    code: 'GF',
    alpha3: 'GUF',
    number: '254',
    name: 'French Guiana',
    i18n: {
      en: 'French Guiana',
      es: 'Guayana Francesa',
    },
    region: 'Americas',
    phoneCode: '594',
    currency: 'EUR',
    locale: 'fra-GF',
    flagEmoji: '🇬🇫',
  },
  {
    code: 'PF',
    alpha3: 'PYF',
    number: '258',
    name: 'French Polynesia',
    i18n: {
      en: 'French Polynesia',
      es: 'Polinesia Francesa',
    },
    region: 'Oceania',
    phoneCode: '689',
    currency: 'XPF',
    locale: 'fra-PF',
    flagEmoji: '🇵🇫',
  },
  {
    code: 'TF',
    alpha3: 'ATF',
    number: '260',
    name: 'French Southern and Antarctic Lands',
    i18n: {
      en: 'French Southern and Antarctic Lands',
      es: 'Tierras Australes y Antárticas Francesas',
    },
    region: 'Oceania',
    phoneCode: '262',
    currency: 'EUR',
    locale: 'fra-TF',
    flagEmoji: '🇹🇫',
  },
  {
    code: 'GA',
    alpha3: 'GAB',
    number: '266',
    name: 'Gabon',
    i18n: {
      en: 'Gabon',
      es: 'Gabón',
    },
    region: 'Africa',
    phoneCode: '241',
    currency: 'XAF',
    locale: 'fra-GA',
    flagEmoji: '🇬🇦',
  },
  {
    code: 'GM',
    alpha3: 'GMB',
    number: '270',
    name: 'Gambia',
    i18n: {
      en: 'Gambia',
      es: 'Gambia',
    },
    region: 'Africa',
    phoneCode: '220',
    currency: 'GMD',
    locale: 'eng-GM',
    flagEmoji: '🇬🇲',
  },
  {
    code: 'GE',
    alpha3: 'GEO',
    number: '268',
    name: 'Georgia',
    i18n: {
      en: 'Georgia',
      es: 'Georgia',
    },
    region: 'Asia',
    phoneCode: '995',
    currency: 'GEL',
    locale: 'kat-GE',
    flagEmoji: '🇬🇪',
  },
  {
    code: 'DE',
    alpha3: 'DEU',
    number: '276',
    name: 'Germany',
    i18n: {
      en: 'Germany',
      es: 'Alemania',
    },
    region: 'Europe',
    phoneCode: '49',
    currency: 'EUR',
    locale: 'deu-DE',
    flagEmoji: '🇩🇪',
  },
  {
    code: 'GH',
    alpha3: 'GHA',
    number: '288',
    name: 'Ghana',
    i18n: {
      en: 'Ghana',
      es: 'Ghana',
    },
    region: 'Africa',
    phoneCode: '233',
    currency: 'GHS',
    locale: 'eng-GH',
    flagEmoji: '🇬🇭',
  },
  {
    code: 'GI',
    alpha3: 'GIB',
    number: '292',
    name: 'Gibraltar',
    i18n: {
      en: 'Gibraltar',
      es: 'Gibraltar',
    },
    region: 'Europe',
    phoneCode: '350',
    currency: 'GIP',
    locale: 'eng-GI',
    flagEmoji: '🇬🇮',
  },
  {
    code: 'GR',
    alpha3: 'GRC',
    number: '300',
    name: 'Greece',
    i18n: {
      en: 'Greece',
      es: 'Grecia',
    },
    region: 'Europe',
    phoneCode: '30',
    currency: 'EUR',
    locale: 'ell-GR',
    flagEmoji: '🇬🇷',
  },
  {
    code: 'GL',
    alpha3: 'GRL',
    number: '304',
    name: 'Greenland',
    i18n: {
      en: 'Greenland',
      es: 'Groenlandia',
    },
    region: 'Americas',
    phoneCode: '299',
    currency: 'DKK',
    locale: 'kal-GL',
    flagEmoji: '🇬🇱',
  },
  {
    code: 'GD',
    alpha3: 'GRD',
    number: '308',
    name: 'Grenada',
    i18n: {
      en: 'Grenada',
      es: 'Grenada',
    },
    region: 'Americas',
    phoneCode: '1473',
    currency: 'XCD',
    locale: 'eng-GD',
    flagEmoji: '🇬🇩',
  },
  {
    code: 'GP',
    alpha3: 'GLP',
    number: '312',
    name: 'Guadeloupe',
    i18n: {
      en: 'Guadeloupe',
      es: 'Guadalupe',
    },
    region: 'Americas',
    phoneCode: '590',
    currency: 'EUR',
    locale: 'fra-GP',
    flagEmoji: '🇬🇵',
  },
  {
    code: 'GU',
    alpha3: 'GUM',
    number: '316',
    name: 'Guam',
    i18n: {
      en: 'Guam',
      es: 'Guam',
    },
    region: 'Oceania',
    phoneCode: '1671',
    currency: 'USD',
    locale: 'cha-GU',
    flagEmoji: '🇬🇺',
  },
  {
    code: 'GT',
    alpha3: 'GTM',
    number: '320',
    name: 'Guatemala',
    i18n: {
      en: 'Guatemala',
      es: 'Guatemala',
    },
    region: 'Americas',
    phoneCode: '502',
    currency: 'GTQ',
    locale: 'spa-GT',
    flagEmoji: '🇬🇹',
  },
  {
    code: 'GG',
    alpha3: 'GGY',
    number: '831',
    name: 'Guernsey',
    i18n: {
      en: 'Guernsey',
      es: 'Guernsey',
    },
    region: 'Europe',
    phoneCode: '44',
    currency: 'GBP',
    locale: 'eng-GG',
    flagEmoji: '🇬🇬',
  },
  {
    code: 'GN',
    alpha3: 'GIN',
    number: '324',
    name: 'Guinea',
    i18n: {
      en: 'Guinea',
      es: 'Guinea',
    },
    region: 'Africa',
    phoneCode: '224',
    currency: 'GNF',
    locale: 'fra-GN',
    flagEmoji: '🇬🇳',
  },
  {
    code: 'GW',
    alpha3: 'GNB',
    number: '624',
    name: 'Guinea-Bissau',
    i18n: {
      en: 'Guinea-Bissau',
      es: 'Guinea-Bisáu',
    },
    region: 'Africa',
    phoneCode: '245',
    currency: 'XOF',
    locale: 'por-GW',
    flagEmoji: '🇬🇼',
  },
  {
    code: 'GY',
    alpha3: 'GUY',
    number: '328',
    name: 'Guyana',
    i18n: {
      en: 'Guyana',
      es: 'Guyana',
    },
    region: 'Americas',
    phoneCode: '592',
    currency: 'GYD',
    locale: 'eng-GY',
    flagEmoji: '🇬🇾',
  },
  {
    code: 'HT',
    alpha3: 'HTI',
    number: '332',
    name: 'Haiti',
    i18n: {
      en: 'Haiti',
      es: 'Haití',
    },
    region: 'Americas',
    phoneCode: '509',
    currency: 'HTG',
    locale: 'fra-HT',
    flagEmoji: '🇭🇹',
  },
  {
    code: 'HM',
    alpha3: 'HMD',
    number: '334',
    name: 'Heard Island and McDonald Islands',
    i18n: {
      en: 'Heard Island and McDonald Islands',
      es: 'Islas Heard y McDonald',
    },
    region: 'Oceania',
    phoneCode: '',
    currency: 'AUD',
    locale: 'eng-HM',
    flagEmoji: '🇭🇲',
  },
  {
    code: 'HN',
    alpha3: 'HND',
    number: '340',
    name: 'Honduras',
    i18n: {
      en: 'Honduras',
      es: 'Honduras',
    },
    region: 'Americas',
    phoneCode: '504',
    currency: 'HNL',
    locale: 'spa-HN',
    flagEmoji: '🇭🇳',
  },
  {
    code: 'HK',
    alpha3: 'HKG',
    number: '344',
    name: 'Hong Kong',
    i18n: {
      en: 'Hong Kong',
      es: 'Hong Kong',
    },
    region: 'Asia',
    phoneCode: '852',
    currency: 'HKD',
    locale: 'eng-HK',
    flagEmoji: '🇭🇰',
  },
  {
    code: 'HU',
    alpha3: 'HUN',
    number: '348',
    name: 'Hungary',
    i18n: {
      en: 'Hungary',
      es: 'Hungría',
    },
    region: 'Europe',
    phoneCode: '36',
    currency: 'HUF',
    locale: 'hun-HU',
    flagEmoji: '🇭🇺',
  },
  {
    code: 'IS',
    alpha3: 'ISL',
    number: '352',
    name: 'Iceland',
    i18n: {
      en: 'Iceland',
      es: 'Islandia',
    },
    region: 'Europe',
    phoneCode: '354',
    currency: 'ISK',
    locale: 'isl-IS',
    flagEmoji: '🇮🇸',
  },
  {
    code: 'IN',
    alpha3: 'IND',
    number: '356',
    name: 'India',
    i18n: {
      en: 'India',
      es: 'India',
    },
    region: 'Asia',
    phoneCode: '91',
    currency: 'INR',
    locale: 'eng-IN',
    flagEmoji: '🇮🇳',
  },
  {
    code: 'ID',
    alpha3: 'IDN',
    number: '360',
    name: 'Indonesia',
    i18n: {
      en: 'Indonesia',
      es: 'Indonesia',
    },
    region: 'Asia',
    phoneCode: '62',
    currency: 'IDR',
    locale: 'ind-ID',
    flagEmoji: '🇮🇩',
  },
  {
    code: 'IR',
    alpha3: 'IRN',
    number: '364',
    name: 'Iran',
    i18n: {
      en: 'Iran',
      es: 'Iran',
    },
    region: 'Asia',
    phoneCode: '98',
    currency: 'IRR',
    locale: 'fas-IR',
    flagEmoji: '🇮🇷',
  },
  {
    code: 'IQ',
    alpha3: 'IRQ',
    number: '368',
    name: 'Iraq',
    i18n: {
      en: 'Iraq',
      es: 'Irak',
    },
    region: 'Asia',
    phoneCode: '964',
    currency: 'IQD',
    locale: 'ara-IQ',
    flagEmoji: '🇮🇶',
  },
  {
    code: 'IE',
    alpha3: 'IRL',
    number: '372',
    name: 'Ireland',
    i18n: {
      en: 'Ireland',
      es: 'Irlanda',
    },
    region: 'Europe',
    phoneCode: '353',
    currency: 'EUR',
    locale: 'eng-IE',
    flagEmoji: '🇮🇪',
  },
  {
    code: 'IM',
    alpha3: 'IMN',
    number: '833',
    name: 'Isle of Man',
    i18n: {
      en: 'Isle of Man',
      es: 'Isla de Man',
    },
    region: 'Europe',
    phoneCode: '44',
    currency: 'GBP',
    locale: 'eng-IM',
    flagEmoji: '🇮🇲',
  },
  {
    code: 'IL',
    alpha3: 'ISR',
    number: '376',
    name: 'Israel',
    i18n: {
      en: 'Israel',
      es: 'Israel',
    },
    region: 'Asia',
    phoneCode: '972',
    currency: 'ILS',
    locale: 'ara-IL',
    flagEmoji: '🇮🇱',
  },
  {
    code: 'IT',
    alpha3: 'ITA',
    number: '380',
    name: 'Italy',
    i18n: {
      en: 'Italy',
      es: 'Italia',
    },
    region: 'Europe',
    phoneCode: '39',
    currency: 'EUR',
    locale: 'ita-IT',
    flagEmoji: '🇮🇹',
  },
  {
    code: 'CI',
    alpha3: 'CIV',
    number: '384',
    name: 'Ivory Coast',
    i18n: {
      en: 'Ivory Coast',
      es: 'Costa de Marfil',
    },
    region: 'Africa',
    phoneCode: '225',
    currency: 'XOF',
    locale: 'fra-CI',
    flagEmoji: '🇨🇮',
  },
  {
    code: 'JM',
    alpha3: 'JAM',
    number: '388',
    name: 'Jamaica',
    i18n: {
      en: 'Jamaica',
      es: 'Jamaica',
    },
    region: 'Americas',
    phoneCode: '1876',
    currency: 'JMD',
    locale: 'eng-JM',
    flagEmoji: '🇯🇲',
  },
  {
    code: 'JP',
    alpha3: 'JPN',
    number: '392',
    name: 'Japan',
    i18n: {
      en: 'Japan',
      es: 'Japón',
    },
    region: 'Asia',
    phoneCode: '81',
    currency: 'JPY',
    locale: 'jpn-JP',
    flagEmoji: '🇯🇵',
  },
  {
    code: 'JE',
    alpha3: 'JEY',
    number: '832',
    name: 'Jersey',
    i18n: {
      en: 'Jersey',
      es: 'Jersey',
    },
    region: 'Europe',
    phoneCode: '44',
    currency: 'GBP',
    locale: 'eng-JE',
    flagEmoji: '🇯🇪',
  },
  {
    code: 'JO',
    alpha3: 'JOR',
    number: '400',
    name: 'Jordan',
    i18n: {
      en: 'Jordan',
      es: 'Jordania',
    },
    region: 'Asia',
    phoneCode: '962',
    currency: 'JOD',
    locale: 'ara-JO',
    flagEmoji: '🇯🇴',
  },
  {
    code: 'KZ',
    alpha3: 'KAZ',
    number: '398',
    name: 'Kazakhstan',
    i18n: {
      en: 'Kazakhstan',
      es: 'Kazajistán',
    },
    region: 'Asia',
    phoneCode: '76',
    currency: 'KZT',
    locale: 'kaz-KZ',
    flagEmoji: '🇰🇿',
  },
  {
    code: 'KE',
    alpha3: 'KEN',
    number: '404',
    name: 'Kenya',
    i18n: {
      en: 'Kenya',
      es: 'Kenia',
    },
    region: 'Africa',
    phoneCode: '254',
    currency: 'KES',
    locale: 'eng-KE',
    flagEmoji: '🇰🇪',
  },
  {
    code: 'KI',
    alpha3: 'KIR',
    number: '296',
    name: 'Kiribati',
    i18n: {
      en: 'Kiribati',
      es: 'Kiribati',
    },
    region: 'Oceania',
    phoneCode: '686',
    currency: 'AUD',
    locale: 'eng-KI',
    flagEmoji: '🇰🇮',
  },
  {
    code: 'XK',
    alpha3: 'UNK',
    number: '',
    name: 'Kosovo',
    i18n: {
      en: 'Kosovo',
      es: 'Kosovo',
    },
    region: 'Europe',
    phoneCode: '383',
    currency: 'EUR',
    locale: 'sqi-XK',
    flagEmoji: '🇽🇰',
  },
  {
    code: 'KW',
    alpha3: 'KWT',
    number: '414',
    name: 'Kuwait',
    i18n: {
      en: 'Kuwait',
      es: 'Kuwait',
    },
    region: 'Asia',
    phoneCode: '965',
    currency: 'KWD',
    locale: 'ara-KW',
    flagEmoji: '🇰🇼',
  },
  {
    code: 'KG',
    alpha3: 'KGZ',
    number: '417',
    name: 'Kyrgyzstan',
    i18n: {
      en: 'Kyrgyzstan',
      es: 'Kirguizistán',
    },
    region: 'Asia',
    phoneCode: '996',
    currency: 'KGS',
    locale: 'kir-KG',
    flagEmoji: '🇰🇬',
  },
  {
    code: 'LA',
    alpha3: 'LAO',
    number: '418',
    name: 'Laos',
    i18n: {
      en: 'Laos',
      es: 'Laos',
    },
    region: 'Asia',
    phoneCode: '856',
    currency: 'LAK',
    locale: 'lao-LA',
    flagEmoji: '🇱🇦',
  },
  {
    code: 'LV',
    alpha3: 'LVA',
    number: '428',
    name: 'Latvia',
    i18n: {
      en: 'Latvia',
      es: 'Letonia',
    },
    region: 'Europe',
    phoneCode: '371',
    currency: 'EUR',
    locale: 'lav-LV',
    flagEmoji: '🇱🇻',
  },
  {
    code: 'LB',
    alpha3: 'LBN',
    number: '422',
    name: 'Lebanon',
    i18n: {
      en: 'Lebanon',
      es: 'Líbano',
    },
    region: 'Asia',
    phoneCode: '961',
    currency: 'LBP',
    locale: 'ara-LB',
    flagEmoji: '🇱🇧',
  },
  {
    code: 'LS',
    alpha3: 'LSO',
    number: '426',
    name: 'Lesotho',
    i18n: {
      en: 'Lesotho',
      es: 'Lesotho',
    },
    region: 'Africa',
    phoneCode: '266',
    currency: 'LSL',
    locale: 'eng-LS',
    flagEmoji: '🇱🇸',
  },
  {
    code: 'LR',
    alpha3: 'LBR',
    number: '430',
    name: 'Liberia',
    i18n: {
      en: 'Liberia',
      es: 'Liberia',
    },
    region: 'Africa',
    phoneCode: '231',
    currency: 'LRD',
    locale: 'eng-LR',
    flagEmoji: '🇱🇷',
  },
  {
    code: 'LY',
    alpha3: 'LBY',
    number: '434',
    name: 'Libya',
    i18n: {
      en: 'Libya',
      es: 'Libia',
    },
    region: 'Africa',
    phoneCode: '218',
    currency: 'LYD',
    locale: 'ara-LY',
    flagEmoji: '🇱🇾',
  },
  {
    code: 'LI',
    alpha3: 'LIE',
    number: '438',
    name: 'Liechtenstein',
    i18n: {
      en: 'Liechtenstein',
      es: 'Liechtenstein',
    },
    region: 'Europe',
    phoneCode: '423',
    currency: 'CHF',
    locale: 'deu-LI',
    flagEmoji: '🇱🇮',
  },
  {
    code: 'LT',
    alpha3: 'LTU',
    number: '440',
    name: 'Lithuania',
    i18n: {
      en: 'Lithuania',
      es: 'Lituania',
    },
    region: 'Europe',
    phoneCode: '370',
    currency: 'EUR',
    locale: 'lit-LT',
    flagEmoji: '🇱🇹',
  },
  {
    code: 'LU',
    alpha3: 'LUX',
    number: '442',
    name: 'Luxembourg',
    i18n: {
      en: 'Luxembourg',
      es: 'Luxemburgo',
    },
    region: 'Europe',
    phoneCode: '352',
    currency: 'EUR',
    locale: 'deu-LU',
    flagEmoji: '🇱🇺',
  },
  {
    code: 'MO',
    alpha3: 'MAC',
    number: '446',
    name: 'Macau',
    i18n: {
      en: 'Macau',
      es: 'Macao',
    },
    region: 'Asia',
    phoneCode: '853',
    currency: 'MOP',
    locale: 'por-MO',
    flagEmoji: '🇲🇴',
  },
  {
    code: 'MG',
    alpha3: 'MDG',
    number: '450',
    name: 'Madagascar',
    i18n: {
      en: 'Madagascar',
      es: 'Madagascar',
    },
    region: 'Africa',
    phoneCode: '261',
    currency: 'MGA',
    locale: 'fra-MG',
    flagEmoji: '🇲🇬',
  },
  {
    code: 'MW',
    alpha3: 'MWI',
    number: '454',
    name: 'Malawi',
    i18n: {
      en: 'Malawi',
      es: 'Malawi',
    },
    region: 'Africa',
    phoneCode: '265',
    currency: 'MWK',
    locale: 'eng-MW',
    flagEmoji: '🇲🇼',
  },
  {
    code: 'MY',
    alpha3: 'MYS',
    number: '458',
    name: 'Malaysia',
    i18n: {
      en: 'Malaysia',
      es: 'Malasia',
    },
    region: 'Asia',
    phoneCode: '60',
    currency: 'MYR',
    locale: 'eng-MY',
    flagEmoji: '🇲🇾',
  },
  {
    code: 'MV',
    alpha3: 'MDV',
    number: '462',
    name: 'Maldives',
    i18n: {
      en: 'Maldives',
      es: 'Maldivas',
    },
    region: 'Asia',
    phoneCode: '960',
    currency: 'MVR',
    locale: 'div-MV',
    flagEmoji: '🇲🇻',
  },
  {
    code: 'ML',
    alpha3: 'MLI',
    number: '466',
    name: 'Mali',
    i18n: {
      en: 'Mali',
      es: 'Mali',
    },
    region: 'Africa',
    phoneCode: '223',
    currency: 'XOF',
    locale: 'fra-ML',
    flagEmoji: '🇲🇱',
  },
  {
    code: 'MT',
    alpha3: 'MLT',
    number: '470',
    name: 'Malta',
    i18n: {
      en: 'Malta',
      es: 'Malta',
    },
    region: 'Europe',
    phoneCode: '356',
    currency: 'EUR',
    locale: 'eng-MT',
    flagEmoji: '🇲🇹',
  },
  {
    code: 'MH',
    alpha3: 'MHL',
    number: '584',
    name: 'Marshall Islands',
    i18n: {
      en: 'Marshall Islands',
      es: 'Islas Marshall',
    },
    region: 'Oceania',
    phoneCode: '692',
    currency: 'USD',
    locale: 'eng-MH',
    flagEmoji: '🇲🇭',
  },
  {
    code: 'MQ',
    alpha3: 'MTQ',
    number: '474',
    name: 'Martinique',
    i18n: {
      en: 'Martinique',
      es: 'Martinica',
    },
    region: 'Americas',
    phoneCode: '596',
    currency: 'EUR',
    locale: 'fra-MQ',
    flagEmoji: '🇲🇶',
  },
  {
    code: 'MR',
    alpha3: 'MRT',
    number: '478',
    name: 'Mauritania',
    i18n: {
      en: 'Mauritania',
      es: 'Mauritania',
    },
    region: 'Africa',
    phoneCode: '222',
    currency: 'MRU',
    locale: 'ara-MR',
    flagEmoji: '🇲🇷',
  },
  {
    code: 'MU',
    alpha3: 'MUS',
    number: '480',
    name: 'Mauritius',
    i18n: {
      en: 'Mauritius',
      es: 'Mauricio',
    },
    region: 'Africa',
    phoneCode: '230',
    currency: 'MUR',
    locale: 'eng-MU',
    flagEmoji: '🇲🇺',
  },
  {
    code: 'YT',
    alpha3: 'MYT',
    number: '175',
    name: 'Mayotte',
    i18n: {
      en: 'Mayotte',
      es: 'Mayotte',
    },
    region: 'Africa',
    phoneCode: '262',
    currency: 'EUR',
    locale: 'fra-YT',
    flagEmoji: '🇾🇹',
  },
  {
    code: 'MX',
    alpha3: 'MEX',
    number: '484',
    name: 'Mexico',
    i18n: {
      en: 'Mexico',
      es: 'México',
    },
    region: 'Americas',
    phoneCode: '52',
    currency: 'MXN',
    locale: 'spa-MX',
    flagEmoji: '🇲🇽',
  },
  {
    code: 'FM',
    alpha3: 'FSM',
    number: '583',
    name: 'Micronesia',
    i18n: {
      en: 'Micronesia',
      es: 'Micronesia',
    },
    region: 'Oceania',
    phoneCode: '691',
    currency: 'USD',
    locale: 'eng-FM',
    flagEmoji: '🇫🇲',
  },
  {
    code: 'MD',
    alpha3: 'MDA',
    number: '498',
    name: 'Moldova',
    i18n: {
      en: 'Moldova',
      es: 'Moldavia',
    },
    region: 'Europe',
    phoneCode: '373',
    currency: 'MDL',
    locale: 'ron-MD',
    flagEmoji: '🇲🇩',
  },
  {
    code: 'MC',
    alpha3: 'MCO',
    number: '492',
    name: 'Monaco',
    i18n: {
      en: 'Monaco',
      es: 'Mónaco',
    },
    region: 'Europe',
    phoneCode: '377',
    currency: 'EUR',
    locale: 'fra-MC',
    flagEmoji: '🇲🇨',
  },
  {
    code: 'MN',
    alpha3: 'MNG',
    number: '496',
    name: 'Mongolia',
    i18n: {
      en: 'Mongolia',
      es: 'Mongolia',
    },
    region: 'Asia',
    phoneCode: '976',
    currency: 'MNT',
    locale: 'mon-MN',
    flagEmoji: '🇲🇳',
  },
  {
    code: 'ME',
    alpha3: 'MNE',
    number: '499',
    name: 'Montenegro',
    i18n: {
      en: 'Montenegro',
      es: 'Montenegro',
    },
    region: 'Europe',
    phoneCode: '382',
    currency: 'EUR',
    locale: 'cnr-ME',
    flagEmoji: '🇲🇪',
  },
  {
    code: 'MS',
    alpha3: 'MSR',
    number: '500',
    name: 'Montserrat',
    i18n: {
      en: 'Montserrat',
      es: 'Montserrat',
    },
    region: 'Americas',
    phoneCode: '1664',
    currency: 'XCD',
    locale: 'eng-MS',
    flagEmoji: '🇲🇸',
  },
  {
    code: 'MA',
    alpha3: 'MAR',
    number: '504',
    name: 'Morocco',
    i18n: {
      en: 'Morocco',
      es: 'Marruecos',
    },
    region: 'Africa',
    phoneCode: '212',
    currency: 'MAD',
    locale: 'ara-MA',
    flagEmoji: '🇲🇦',
  },
  {
    code: 'MZ',
    alpha3: 'MOZ',
    number: '508',
    name: 'Mozambique',
    i18n: {
      en: 'Mozambique',
      es: 'Mozambique',
    },
    region: 'Africa',
    phoneCode: '258',
    currency: 'MZN',
    locale: 'por-MZ',
    flagEmoji: '🇲🇿',
  },
  {
    code: 'MM',
    alpha3: 'MMR',
    number: '104',
    name: 'Myanmar',
    i18n: {
      en: 'Myanmar',
      es: 'Myanmar',
    },
    region: 'Asia',
    phoneCode: '95',
    currency: 'MMK',
    locale: 'mya-MM',
    flagEmoji: '🇲🇲',
  },
  {
    code: 'NA',
    alpha3: 'NAM',
    number: '516',
    name: 'Namibia',
    i18n: {
      en: 'Namibia',
      es: 'Namibia',
    },
    region: 'Africa',
    phoneCode: '264',
    currency: 'NAD',
    locale: 'afr-NA',
    flagEmoji: '🇳🇦',
  },
  {
    code: 'NR',
    alpha3: 'NRU',
    number: '520',
    name: 'Nauru',
    i18n: {
      en: 'Nauru',
      es: 'Nauru',
    },
    region: 'Oceania',
    phoneCode: '674',
    currency: 'AUD',
    locale: 'eng-NR',
    flagEmoji: '🇳🇷',
  },
  {
    code: 'NP',
    alpha3: 'NPL',
    number: '524',
    name: 'Nepal',
    i18n: {
      en: 'Nepal',
      es: 'Nepal',
    },
    region: 'Asia',
    phoneCode: '977',
    currency: 'NPR',
    locale: 'nep-NP',
    flagEmoji: '🇳🇵',
  },
  {
    code: 'NL',
    alpha3: 'NLD',
    number: '528',
    name: 'Netherlands',
    i18n: {
      en: 'Netherlands',
      es: 'Países Bajos',
    },
    region: 'Europe',
    phoneCode: '31',
    currency: 'EUR',
    locale: 'nld-NL',
    flagEmoji: '🇳🇱',
  },
  {
    code: 'NC',
    alpha3: 'NCL',
    number: '540',
    name: 'New Caledonia',
    i18n: {
      en: 'New Caledonia',
      es: 'Nueva Caledonia',
    },
    region: 'Oceania',
    phoneCode: '687',
    currency: 'XPF',
    locale: 'fra-NC',
    flagEmoji: '🇳🇨',
  },
  {
    code: 'NZ',
    alpha3: 'NZL',
    number: '554',
    name: 'New Zealand',
    i18n: {
      en: 'New Zealand',
      es: 'Nueva Zelanda',
    },
    region: 'Oceania',
    phoneCode: '64',
    currency: 'NZD',
    locale: 'eng-NZ',
    flagEmoji: '🇳🇿',
  },
  {
    code: 'NI',
    alpha3: 'NIC',
    number: '558',
    name: 'Nicaragua',
    i18n: {
      en: 'Nicaragua',
      es: 'Nicaragua',
    },
    region: 'Americas',
    phoneCode: '505',
    currency: 'NIO',
    locale: 'spa-NI',
    flagEmoji: '🇳🇮',
  },
  {
    code: 'NE',
    alpha3: 'NER',
    number: '562',
    name: 'Niger',
    i18n: {
      en: 'Niger',
      es: 'Níger',
    },
    region: 'Africa',
    phoneCode: '227',
    currency: 'XOF',
    locale: 'fra-NE',
    flagEmoji: '🇳🇪',
  },
  {
    code: 'NG',
    alpha3: 'NGA',
    number: '566',
    name: 'Nigeria',
    i18n: {
      en: 'Nigeria',
      es: 'Nigeria',
    },
    region: 'Africa',
    phoneCode: '234',
    currency: 'NGN',
    locale: 'eng-NG',
    flagEmoji: '🇳🇬',
  },
  {
    code: 'NU',
    alpha3: 'NIU',
    number: '570',
    name: 'Niue',
    i18n: {
      en: 'Niue',
      es: 'Niue',
    },
    region: 'Oceania',
    phoneCode: '683',
    currency: 'NZD',
    locale: 'eng-NU',
    flagEmoji: '🇳🇺',
  },
  {
    code: 'NF',
    alpha3: 'NFK',
    number: '574',
    name: 'Norfolk Island',
    i18n: {
      en: 'Norfolk Island',
      es: 'Isla de Norfolk',
    },
    region: 'Oceania',
    phoneCode: '672',
    currency: 'AUD',
    locale: 'eng-NF',
    flagEmoji: '🇳🇫',
  },
  {
    code: 'KP',
    alpha3: 'PRK',
    number: '408',
    name: 'North Korea',
    i18n: {
      en: 'North Korea',
      es: 'Corea del Norte',
    },
    region: 'Asia',
    phoneCode: '850',
    currency: 'KPW',
    locale: 'kor-KP',
    flagEmoji: '🇰🇵',
  },
  {
    code: 'MK',
    alpha3: 'MKD',
    number: '807',
    name: 'North Macedonia',
    i18n: {
      en: 'North Macedonia',
      es: 'Macedonia del Norte',
    },
    region: 'Europe',
    phoneCode: '389',
    currency: 'MKD',
    locale: 'mkd-MK',
    flagEmoji: '🇲🇰',
  },
  {
    code: 'MP',
    alpha3: 'MNP',
    number: '580',
    name: 'Northern Mariana Islands',
    i18n: {
      en: 'Northern Mariana Islands',
      es: 'Islas Marianas del Norte',
    },
    region: 'Oceania',
    phoneCode: '1670',
    currency: 'USD',
    locale: 'cal-MP',
    flagEmoji: '🇲🇵',
  },
  {
    code: 'NO',
    alpha3: 'NOR',
    number: '578',
    name: 'Norway',
    i18n: {
      en: 'Norway',
      es: 'Noruega',
    },
    region: 'Europe',
    phoneCode: '47',
    currency: 'NOK',
    locale: 'nno-NO',
    flagEmoji: '🇳🇴',
  },
  {
    code: 'OM',
    alpha3: 'OMN',
    number: '512',
    name: 'Oman',
    i18n: {
      en: 'Oman',
      es: 'Omán',
    },
    region: 'Asia',
    phoneCode: '968',
    currency: 'OMR',
    locale: 'ara-OM',
    flagEmoji: '🇴🇲',
  },
  {
    code: 'PK',
    alpha3: 'PAK',
    number: '586',
    name: 'Pakistan',
    i18n: {
      en: 'Pakistan',
      es: 'Pakistán',
    },
    region: 'Asia',
    phoneCode: '92',
    currency: 'PKR',
    locale: 'eng-PK',
    flagEmoji: '🇵🇰',
  },
  {
    code: 'PW',
    alpha3: 'PLW',
    number: '585',
    name: 'Palau',
    i18n: {
      en: 'Palau',
      es: 'Palau',
    },
    region: 'Oceania',
    phoneCode: '680',
    currency: 'USD',
    locale: 'eng-PW',
    flagEmoji: '🇵🇼',
  },
  {
    code: 'PS',
    alpha3: 'PSE',
    number: '275',
    name: 'Palestine',
    i18n: {
      en: 'Palestine',
      es: 'Palestina',
    },
    region: 'Asia',
    phoneCode: '970',
    currency: 'EGP',
    locale: 'ara-PS',
    flagEmoji: '🇵🇸',
  },
  {
    code: 'PA',
    alpha3: 'PAN',
    number: '591',
    name: 'Panama',
    i18n: {
      en: 'Panama',
      es: 'Panamá',
    },
    region: 'Americas',
    phoneCode: '507',
    currency: 'PAB',
    locale: 'spa-PA',
    flagEmoji: '🇵🇦',
  },
  {
    code: 'PG',
    alpha3: 'PNG',
    number: '598',
    name: 'Papua New Guinea',
    i18n: {
      en: 'Papua New Guinea',
      es: 'Papúa Nueva Guinea',
    },
    region: 'Oceania',
    phoneCode: '675',
    currency: 'PGK',
    locale: 'eng-PG',
    flagEmoji: '🇵🇬',
  },
  {
    code: 'PY',
    alpha3: 'PRY',
    number: '600',
    name: 'Paraguay',
    i18n: {
      en: 'Paraguay',
      es: 'Paraguay',
    },
    region: 'Americas',
    phoneCode: '595',
    currency: 'PYG',
    locale: 'grn-PY',
    flagEmoji: '🇵🇾',
  },
  {
    code: 'PE',
    alpha3: 'PER',
    number: '604',
    name: 'Peru',
    i18n: {
      en: 'Peru',
      es: 'Perú',
    },
    region: 'Americas',
    phoneCode: '51',
    currency: 'PEN',
    locale: 'aym-PE',
    flagEmoji: '🇵🇪',
  },
  {
    code: 'PH',
    alpha3: 'PHL',
    number: '608',
    name: 'Philippines',
    i18n: {
      en: 'Philippines',
      es: 'Filipinas',
    },
    region: 'Asia',
    phoneCode: '63',
    currency: 'PHP',
    locale: 'eng-PH',
    flagEmoji: '🇵🇭',
  },
  {
    code: 'PN',
    alpha3: 'PCN',
    number: '612',
    name: 'Pitcairn Islands',
    i18n: {
      en: 'Pitcairn Islands',
      es: 'Islas Pitcairn',
    },
    region: 'Oceania',
    phoneCode: '64',
    currency: 'NZD',
    locale: 'eng-PN',
    flagEmoji: '🇵🇳',
  },
  {
    code: 'PL',
    alpha3: 'POL',
    number: '616',
    name: 'Poland',
    i18n: {
      en: 'Poland',
      es: 'Polonia',
    },
    region: 'Europe',
    phoneCode: '48',
    currency: 'PLN',
    locale: 'pol-PL',
    flagEmoji: '🇵🇱',
  },
  {
    code: 'PT',
    alpha3: 'PRT',
    number: '620',
    name: 'Portugal',
    i18n: {
      en: 'Portugal',
      es: 'Portugal',
    },
    region: 'Europe',
    phoneCode: '351',
    currency: 'EUR',
    locale: 'por-PT',
    flagEmoji: '🇵🇹',
  },
  {
    code: 'PR',
    alpha3: 'PRI',
    number: '630',
    name: 'Puerto Rico',
    i18n: {
      en: 'Puerto Rico',
      es: 'Puerto Rico',
    },
    region: 'Americas',
    phoneCode: '1787',
    currency: 'USD',
    locale: 'eng-PR',
    flagEmoji: '🇵🇷',
  },
  {
    code: 'QA',
    alpha3: 'QAT',
    number: '634',
    name: 'Qatar',
    i18n: {
      en: 'Qatar',
      es: 'Catar',
    },
    region: 'Asia',
    phoneCode: '974',
    currency: 'QAR',
    locale: 'ara-QA',
    flagEmoji: '🇶🇦',
  },
  {
    code: 'CG',
    alpha3: 'COG',
    number: '178',
    name: 'Republic of the Congo',
    i18n: {
      en: 'Republic of the Congo',
      es: 'Congo',
    },
    region: 'Africa',
    phoneCode: '242',
    currency: 'XAF',
    locale: 'fra-CG',
    flagEmoji: '🇨🇬',
  },
  {
    code: 'RE',
    alpha3: 'REU',
    number: '638',
    name: 'Réunion',
    i18n: {
      en: 'Réunion',
      es: 'Reunión',
    },
    region: 'Africa',
    phoneCode: '262',
    currency: 'EUR',
    locale: 'fra-RE',
    flagEmoji: '🇷🇪',
  },
  {
    code: 'RO',
    alpha3: 'ROU',
    number: '642',
    name: 'Romania',
    i18n: {
      en: 'Romania',
      es: 'Rumania',
    },
    region: 'Europe',
    phoneCode: '40',
    currency: 'RON',
    locale: 'ron-RO',
    flagEmoji: '🇷🇴',
  },
  {
    code: 'RU',
    alpha3: 'RUS',
    number: '643',
    name: 'Russia',
    i18n: {
      en: 'Russia',
      es: 'Rusia',
    },
    region: 'Europe',
    phoneCode: '73',
    currency: 'RUB',
    locale: 'rus-RU',
    flagEmoji: '🇷🇺',
  },
  {
    code: 'RW',
    alpha3: 'RWA',
    number: '646',
    name: 'Rwanda',
    i18n: {
      en: 'Rwanda',
      es: 'Ruanda',
    },
    region: 'Africa',
    phoneCode: '250',
    currency: 'RWF',
    locale: 'eng-RW',
    flagEmoji: '🇷🇼',
  },
  {
    code: 'BL',
    alpha3: 'BLM',
    number: '652',
    name: 'Saint Barthélemy',
    i18n: {
      en: 'Saint Barthélemy',
      es: 'San Bartolomé',
    },
    region: 'Americas',
    phoneCode: '590',
    currency: 'EUR',
    locale: 'fra-BL',
    flagEmoji: '🇧🇱',
  },
  {
    code: 'SH',
    alpha3: 'SHN',
    number: '654',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    i18n: {
      en: 'Saint Helena, Ascension and Tristan da Cunha',
      es: 'Santa Elena, Ascensión y Tristán de Acuña',
    },
    region: 'Africa',
    phoneCode: '290',
    currency: 'GBP',
    locale: 'eng-SH',
    flagEmoji: '🇸🇭',
  },
  {
    code: 'KN',
    alpha3: 'KNA',
    number: '659',
    name: 'Saint Kitts and Nevis',
    i18n: {
      en: 'Saint Kitts and Nevis',
      es: 'San Cristóbal y Nieves',
    },
    region: 'Americas',
    phoneCode: '1869',
    currency: 'XCD',
    locale: 'eng-KN',
    flagEmoji: '🇰🇳',
  },
  {
    code: 'LC',
    alpha3: 'LCA',
    number: '662',
    name: 'Saint Lucia',
    i18n: {
      en: 'Saint Lucia',
      es: 'Santa Lucía',
    },
    region: 'Americas',
    phoneCode: '1758',
    currency: 'XCD',
    locale: 'eng-LC',
    flagEmoji: '🇱🇨',
  },
  {
    code: 'MF',
    alpha3: 'MAF',
    number: '663',
    name: 'Saint Martin',
    i18n: {
      en: 'Saint Martin',
      es: 'Saint Martin',
    },
    region: 'Americas',
    phoneCode: '590',
    currency: 'EUR',
    locale: 'fra-MF',
    flagEmoji: '🇲🇫',
  },
  {
    code: 'PM',
    alpha3: 'SPM',
    number: '666',
    name: 'Saint Pierre and Miquelon',
    i18n: {
      en: 'Saint Pierre and Miquelon',
      es: 'San Pedro y Miquelón',
    },
    region: 'Americas',
    phoneCode: '508',
    currency: 'EUR',
    locale: 'fra-PM',
    flagEmoji: '🇵🇲',
  },
  {
    code: 'VC',
    alpha3: 'VCT',
    number: '670',
    name: 'Saint Vincent and the Grenadines',
    i18n: {
      en: 'Saint Vincent and the Grenadines',
      es: 'San Vicente y Granadinas',
    },
    region: 'Americas',
    phoneCode: '1784',
    currency: 'XCD',
    locale: 'eng-VC',
    flagEmoji: '🇻🇨',
  },
  {
    code: 'WS',
    alpha3: 'WSM',
    number: '882',
    name: 'Samoa',
    i18n: {
      en: 'Samoa',
      es: 'Samoa',
    },
    region: 'Oceania',
    phoneCode: '685',
    currency: 'WST',
    locale: 'eng-WS',
    flagEmoji: '🇼🇸',
  },
  {
    code: 'SM',
    alpha3: 'SMR',
    number: '674',
    name: 'San Marino',
    i18n: {
      en: 'San Marino',
      es: 'San Marino',
    },
    region: 'Europe',
    phoneCode: '378',
    currency: 'EUR',
    locale: 'ita-SM',
    flagEmoji: '🇸🇲',
  },
  {
    code: 'ST',
    alpha3: 'STP',
    number: '678',
    name: 'São Tomé and Príncipe',
    i18n: {
      en: 'São Tomé and Príncipe',
      es: 'Santo Tomé y Príncipe',
    },
    region: 'Africa',
    phoneCode: '239',
    currency: 'STN',
    locale: 'por-ST',
    flagEmoji: '🇸🇹',
  },
  {
    code: 'SA',
    alpha3: 'SAU',
    number: '682',
    name: 'Saudi Arabia',
    i18n: {
      en: 'Saudi Arabia',
      es: 'Arabia Saudí',
    },
    region: 'Asia',
    phoneCode: '966',
    currency: 'SAR',
    locale: 'ara-SA',
    flagEmoji: '🇸🇦',
  },
  {
    code: 'SN',
    alpha3: 'SEN',
    number: '686',
    name: 'Senegal',
    i18n: {
      en: 'Senegal',
      es: 'Senegal',
    },
    region: 'Africa',
    phoneCode: '221',
    currency: 'XOF',
    locale: 'fra-SN',
    flagEmoji: '🇸🇳',
  },
  {
    code: 'RS',
    alpha3: 'SRB',
    number: '688',
    name: 'Serbia',
    i18n: {
      en: 'Serbia',
      es: 'Serbia',
    },
    region: 'Europe',
    phoneCode: '381',
    currency: 'RSD',
    locale: 'srp-RS',
    flagEmoji: '🇷🇸',
  },
  {
    code: 'SC',
    alpha3: 'SYC',
    number: '690',
    name: 'Seychelles',
    i18n: {
      en: 'Seychelles',
      es: 'Seychelles',
    },
    region: 'Africa',
    phoneCode: '248',
    currency: 'SCR',
    locale: 'crs-SC',
    flagEmoji: '🇸🇨',
  },
  {
    code: 'SL',
    alpha3: 'SLE',
    number: '694',
    name: 'Sierra Leone',
    i18n: {
      en: 'Sierra Leone',
      es: 'Sierra Leone',
    },
    region: 'Africa',
    phoneCode: '232',
    currency: 'SLE',
    locale: 'eng-SL',
    flagEmoji: '🇸🇱',
  },
  {
    code: 'SG',
    alpha3: 'SGP',
    number: '702',
    name: 'Singapore',
    i18n: {
      en: 'Singapore',
      es: 'Singapur',
    },
    region: 'Asia',
    phoneCode: '65',
    currency: 'SGD',
    locale: 'eng-SG',
    flagEmoji: '🇸🇬',
  },
  {
    code: 'SX',
    alpha3: 'SXM',
    number: '534',
    name: 'Sint Maarten',
    i18n: {
      en: 'Sint Maarten',
      es: 'Sint Maarten',
    },
    region: 'Americas',
    phoneCode: '1721',
    currency: 'ANG',
    locale: 'eng-SX',
    flagEmoji: '🇸🇽',
  },
  {
    code: 'SK',
    alpha3: 'SVK',
    number: '703',
    name: 'Slovakia',
    i18n: {
      en: 'Slovakia',
      es: 'República Eslovaca',
    },
    region: 'Europe',
    phoneCode: '421',
    currency: 'EUR',
    locale: 'slk-SK',
    flagEmoji: '🇸🇰',
  },
  {
    code: 'SI',
    alpha3: 'SVN',
    number: '705',
    name: 'Slovenia',
    i18n: {
      en: 'Slovenia',
      es: 'Eslovenia',
    },
    region: 'Europe',
    phoneCode: '386',
    currency: 'EUR',
    locale: 'slv-SI',
    flagEmoji: '🇸🇮',
  },
  {
    code: 'SB',
    alpha3: 'SLB',
    number: '090',
    name: 'Solomon Islands',
    i18n: {
      en: 'Solomon Islands',
      es: 'Islas Salomón',
    },
    region: 'Oceania',
    phoneCode: '677',
    currency: 'SBD',
    locale: 'eng-SB',
    flagEmoji: '🇸🇧',
  },
  {
    code: 'SO',
    alpha3: 'SOM',
    number: '706',
    name: 'Somalia',
    i18n: {
      en: 'Somalia',
      es: 'Somalia',
    },
    region: 'Africa',
    phoneCode: '252',
    currency: 'SOS',
    locale: 'ara-SO',
    flagEmoji: '🇸🇴',
  },
  {
    code: 'ZA',
    alpha3: 'ZAF',
    number: '710',
    name: 'South Africa',
    i18n: {
      en: 'South Africa',
      es: 'Sudáfrica',
    },
    region: 'Africa',
    phoneCode: '27',
    currency: 'ZAR',
    locale: 'afr-ZA',
    flagEmoji: '🇿🇦',
  },
  {
    code: 'GS',
    alpha3: 'SGS',
    number: '239',
    name: 'South Georgia',
    i18n: {
      en: 'South Georgia',
      es: 'Islas Georgias del Sur y Sandwich del Sur',
    },
    region: 'Oceania',
    phoneCode: '500',
    currency: 'GBP',
    locale: 'eng-GS',
    flagEmoji: '🇬🇸',
  },
  {
    code: 'KR',
    alpha3: 'KOR',
    number: '410',
    name: 'South Korea',
    i18n: {
      en: 'South Korea',
      es: 'Corea del Sur',
    },
    region: 'Asia',
    phoneCode: '82',
    currency: 'KRW',
    locale: 'kor-KR',
    flagEmoji: '🇰🇷',
  },
  {
    code: 'SS',
    alpha3: 'SSD',
    number: '728',
    name: 'South Sudan',
    i18n: {
      en: 'South Sudan',
      es: 'Sudán del Sur',
    },
    region: 'Africa',
    phoneCode: '211',
    currency: 'SSP',
    locale: 'eng-SS',
    flagEmoji: '🇸🇸',
  },
  {
    code: 'ES',
    alpha3: 'ESP',
    number: '724',
    name: 'Spain',
    i18n: {
      en: 'Spain',
      es: 'España',
    },
    region: 'Europe',
    phoneCode: '34',
    currency: 'EUR',
    locale: 'spa-ES',
    flagEmoji: '🇪🇸',
  },
  {
    code: 'LK',
    alpha3: 'LKA',
    number: '144',
    name: 'Sri Lanka',
    i18n: {
      en: 'Sri Lanka',
      es: 'Sri Lanka',
    },
    region: 'Asia',
    phoneCode: '94',
    currency: 'LKR',
    locale: 'sin-LK',
    flagEmoji: '🇱🇰',
  },
  {
    code: 'SD',
    alpha3: 'SDN',
    number: '729',
    name: 'Sudan',
    i18n: {
      en: 'Sudan',
      es: 'Sudán',
    },
    region: 'Africa',
    phoneCode: '249',
    currency: 'SDG',
    locale: 'ara-SD',
    flagEmoji: '🇸🇩',
  },
  {
    code: 'SR',
    alpha3: 'SUR',
    number: '740',
    name: 'Suriname',
    i18n: {
      en: 'Suriname',
      es: 'Surinam',
    },
    region: 'Americas',
    phoneCode: '597',
    currency: 'SRD',
    locale: 'nld-SR',
    flagEmoji: '🇸🇷',
  },
  {
    code: 'SJ',
    alpha3: 'SJM',
    number: '744',
    name: 'Svalbard and Jan Mayen',
    i18n: {
      en: 'Svalbard and Jan Mayen',
      es: 'Islas Svalbard y Jan Mayen',
    },
    region: 'Europe',
    phoneCode: '4779',
    currency: 'NOK',
    locale: 'nor-SJ',
    flagEmoji: '🇸🇯',
  },
  {
    code: 'SE',
    alpha3: 'SWE',
    number: '752',
    name: 'Sweden',
    i18n: {
      en: 'Sweden',
      es: 'Suecia',
    },
    region: 'Europe',
    phoneCode: '46',
    currency: 'SEK',
    locale: 'swe-SE',
    flagEmoji: '🇸🇪',
  },
  {
    code: 'CH',
    alpha3: 'CHE',
    number: '756',
    name: 'Switzerland',
    i18n: {
      en: 'Switzerland',
      es: 'Suiza',
    },
    region: 'Europe',
    phoneCode: '41',
    currency: 'CHF',
    locale: 'fra-CH',
    flagEmoji: '🇨🇭',
  },
  {
    code: 'SY',
    alpha3: 'SYR',
    number: '760',
    name: 'Syria',
    i18n: {
      en: 'Syria',
      es: 'Siria',
    },
    region: 'Asia',
    phoneCode: '963',
    currency: 'SYP',
    locale: 'ara-SY',
    flagEmoji: '🇸🇾',
  },
  {
    code: 'TW',
    alpha3: 'TWN',
    number: '158',
    name: 'Taiwan',
    i18n: {
      en: 'Taiwan',
      es: 'Taiwán',
    },
    region: 'Asia',
    phoneCode: '886',
    currency: 'TWD',
    locale: 'zho-TW',
    flagEmoji: '🇹🇼',
  },
  {
    code: 'TJ',
    alpha3: 'TJK',
    number: '762',
    name: 'Tajikistan',
    i18n: {
      en: 'Tajikistan',
      es: 'Tayikistán',
    },
    region: 'Asia',
    phoneCode: '992',
    currency: 'TJS',
    locale: 'rus-TJ',
    flagEmoji: '🇹🇯',
  },
  {
    code: 'TZ',
    alpha3: 'TZA',
    number: '834',
    name: 'Tanzania',
    i18n: {
      en: 'Tanzania',
      es: 'Tanzania',
    },
    region: 'Africa',
    phoneCode: '255',
    currency: 'TZS',
    locale: 'eng-TZ',
    flagEmoji: '🇹🇿',
  },
  {
    code: 'TH',
    alpha3: 'THA',
    number: '764',
    name: 'Thailand',
    i18n: {
      en: 'Thailand',
      es: 'Tailandia',
    },
    region: 'Asia',
    phoneCode: '66',
    currency: 'THB',
    locale: 'tha-TH',
    flagEmoji: '🇹🇭',
  },
  {
    code: 'TL',
    alpha3: 'TLS',
    number: '626',
    name: 'Timor-Leste',
    i18n: {
      en: 'Timor-Leste',
      es: 'Timor Oriental',
    },
    region: 'Asia',
    phoneCode: '670',
    currency: 'USD',
    locale: 'por-TL',
    flagEmoji: '🇹🇱',
  },
  {
    code: 'TG',
    alpha3: 'TGO',
    number: '768',
    name: 'Togo',
    i18n: {
      en: 'Togo',
      es: 'Togo',
    },
    region: 'Africa',
    phoneCode: '228',
    currency: 'XOF',
    locale: 'fra-TG',
    flagEmoji: '🇹🇬',
  },
  {
    code: 'TK',
    alpha3: 'TKL',
    number: '772',
    name: 'Tokelau',
    i18n: {
      en: 'Tokelau',
      es: 'Islas Tokelau',
    },
    region: 'Oceania',
    phoneCode: '690',
    currency: 'NZD',
    locale: 'eng-TK',
    flagEmoji: '🇹🇰',
  },
  {
    code: 'TO',
    alpha3: 'TON',
    number: '776',
    name: 'Tonga',
    i18n: {
      en: 'Tonga',
      es: 'Tonga',
    },
    region: 'Oceania',
    phoneCode: '676',
    currency: 'TOP',
    locale: 'eng-TO',
    flagEmoji: '🇹🇴',
  },
  {
    code: 'TT',
    alpha3: 'TTO',
    number: '780',
    name: 'Trinidad and Tobago',
    i18n: {
      en: 'Trinidad and Tobago',
      es: 'Trinidad y Tobago',
    },
    region: 'Americas',
    phoneCode: '1868',
    currency: 'TTD',
    locale: 'eng-TT',
    flagEmoji: '🇹🇹',
  },
  {
    code: 'TN',
    alpha3: 'TUN',
    number: '788',
    name: 'Tunisia',
    i18n: {
      en: 'Tunisia',
      es: 'Túnez',
    },
    region: 'Africa',
    phoneCode: '216',
    currency: 'TND',
    locale: 'ara-TN',
    flagEmoji: '🇹🇳',
  },
  {
    code: 'TR',
    alpha3: 'TUR',
    number: '792',
    name: 'Turkey',
    i18n: {
      en: 'Turkey',
      es: 'Turquía',
    },
    region: 'Asia',
    phoneCode: '90',
    currency: 'TRY',
    locale: 'tur-TR',
    flagEmoji: '🇹🇷',
  },
  {
    code: 'TM',
    alpha3: 'TKM',
    number: '795',
    name: 'Turkmenistan',
    i18n: {
      en: 'Turkmenistan',
      es: 'Turkmenistán',
    },
    region: 'Asia',
    phoneCode: '993',
    currency: 'TMT',
    locale: 'rus-TM',
    flagEmoji: '🇹🇲',
  },
  {
    code: 'TC',
    alpha3: 'TCA',
    number: '796',
    name: 'Turks and Caicos Islands',
    i18n: {
      en: 'Turks and Caicos Islands',
      es: 'Islas Turks y Caicos',
    },
    region: 'Americas',
    phoneCode: '1649',
    currency: 'USD',
    locale: 'eng-TC',
    flagEmoji: '🇹🇨',
  },
  {
    code: 'TV',
    alpha3: 'TUV',
    number: '798',
    name: 'Tuvalu',
    i18n: {
      en: 'Tuvalu',
      es: 'Tuvalu',
    },
    region: 'Oceania',
    phoneCode: '688',
    currency: 'AUD',
    locale: 'eng-TV',
    flagEmoji: '🇹🇻',
  },
  {
    code: 'UG',
    alpha3: 'UGA',
    number: '800',
    name: 'Uganda',
    i18n: {
      en: 'Uganda',
      es: 'Uganda',
    },
    region: 'Africa',
    phoneCode: '256',
    currency: 'UGX',
    locale: 'eng-UG',
    flagEmoji: '🇺🇬',
  },
  {
    code: 'UA',
    alpha3: 'UKR',
    number: '804',
    name: 'Ukraine',
    i18n: {
      en: 'Ukraine',
      es: 'Ucrania',
    },
    region: 'Europe',
    phoneCode: '380',
    currency: 'UAH',
    locale: 'ukr-UA',
    flagEmoji: '🇺🇦',
  },
  {
    code: 'AE',
    alpha3: 'ARE',
    number: '784',
    name: 'United Arab Emirates',
    i18n: {
      en: 'United Arab Emirates',
      es: 'Emiratos Árabes Unidos',
    },
    region: 'Asia',
    phoneCode: '971',
    currency: 'AED',
    locale: 'ara-AE',
    flagEmoji: '🇦🇪',
  },
  {
    code: 'GB',
    alpha3: 'GBR',
    number: '826',
    name: 'United Kingdom',
    i18n: {
      en: 'United Kingdom',
      es: 'Reino Unido',
    },
    region: 'Europe',
    phoneCode: '44',
    currency: 'GBP',
    locale: 'eng-GB',
    flagEmoji: '🇬🇧',
  },
  {
    code: 'US',
    alpha3: 'USA',
    number: '840',
    name: 'United States',
    i18n: {
      en: 'United States',
      es: 'Estados Unidos',
    },
    region: 'Americas',
    phoneCode: '1201',
    currency: 'USD',
    locale: 'eng-US',
    flagEmoji: '🇺🇸',
  },
  {
    code: 'UM',
    alpha3: 'UMI',
    number: '581',
    name: 'United States Minor Outlying Islands',
    i18n: {
      en: 'United States Minor Outlying Islands',
      es: 'Islas Ultramarinas Menores de Estados Unidos',
    },
    region: 'Americas',
    phoneCode: '268',
    currency: 'USD',
    locale: 'eng-UM',
    flagEmoji: '🇺🇲',
  },
  {
    code: 'VI',
    alpha3: 'VIR',
    number: '850',
    name: 'United States Virgin Islands',
    i18n: {
      en: 'United States Virgin Islands',
      es: 'Islas Vírgenes de los Estados Unidos',
    },
    region: 'Americas',
    phoneCode: '1340',
    currency: 'USD',
    locale: 'eng-VI',
    flagEmoji: '🇻🇮',
  },
  {
    code: 'UY',
    alpha3: 'URY',
    number: '858',
    name: 'Uruguay',
    i18n: {
      en: 'Uruguay',
      es: 'Uruguay',
    },
    region: 'Americas',
    phoneCode: '598',
    currency: 'UYU',
    locale: 'spa-UY',
    flagEmoji: '🇺🇾',
  },
  {
    code: 'UZ',
    alpha3: 'UZB',
    number: '860',
    name: 'Uzbekistan',
    i18n: {
      en: 'Uzbekistan',
      es: 'Uzbekistán',
    },
    region: 'Asia',
    phoneCode: '998',
    currency: 'UZS',
    locale: 'rus-UZ',
    flagEmoji: '🇺🇿',
  },
  {
    code: 'VU',
    alpha3: 'VUT',
    number: '548',
    name: 'Vanuatu',
    i18n: {
      en: 'Vanuatu',
      es: 'Vanuatu',
    },
    region: 'Oceania',
    phoneCode: '678',
    currency: 'VUV',
    locale: 'bis-VU',
    flagEmoji: '🇻🇺',
  },
  {
    code: 'VA',
    alpha3: 'VAT',
    number: '336',
    name: 'Vatican City',
    i18n: {
      en: 'Vatican City',
      es: 'Ciudad del Vaticano',
    },
    region: 'Europe',
    phoneCode: '3906698',
    currency: 'EUR',
    locale: 'ita-VA',
    flagEmoji: '🇻🇦',
  },
  {
    code: 'VE',
    alpha3: 'VEN',
    number: '862',
    name: 'Venezuela',
    i18n: {
      en: 'Venezuela',
      es: 'Venezuela',
    },
    region: 'Americas',
    phoneCode: '58',
    currency: 'VES',
    locale: 'spa-VE',
    flagEmoji: '🇻🇪',
  },
  {
    code: 'VN',
    alpha3: 'VNM',
    number: '704',
    name: 'Vietnam',
    i18n: {
      en: 'Vietnam',
      es: 'Vietnam',
    },
    region: 'Asia',
    phoneCode: '84',
    currency: 'VND',
    locale: 'vie-VN',
    flagEmoji: '🇻🇳',
  },
  {
    code: 'WF',
    alpha3: 'WLF',
    number: '876',
    name: 'Wallis and Futuna',
    i18n: {
      en: 'Wallis and Futuna',
      es: 'Wallis y Futuna',
    },
    region: 'Oceania',
    phoneCode: '681',
    currency: 'XPF',
    locale: 'fra-WF',
    flagEmoji: '🇼🇫',
  },
  {
    code: 'EH',
    alpha3: 'ESH',
    number: '732',
    name: 'Western Sahara',
    i18n: {
      en: 'Western Sahara',
      es: 'Sahara Occidental',
    },
    region: 'Africa',
    phoneCode: '2125288',
    currency: 'DZD',
    locale: 'ber-EH',
    flagEmoji: '🇪🇭',
  },
  {
    code: 'YE',
    alpha3: 'YEM',
    number: '887',
    name: 'Yemen',
    i18n: {
      en: 'Yemen',
      es: 'Yemen',
    },
    region: 'Asia',
    phoneCode: '967',
    currency: 'YER',
    locale: 'ara-YE',
    flagEmoji: '🇾🇪',
  },
  {
    code: 'ZM',
    alpha3: 'ZMB',
    number: '894',
    name: 'Zambia',
    i18n: {
      en: 'Zambia',
      es: 'Zambia',
    },
    region: 'Africa',
    phoneCode: '260',
    currency: 'ZMW',
    locale: 'eng-ZM',
    flagEmoji: '🇿🇲',
  },
  {
    code: 'ZW',
    alpha3: 'ZWE',
    number: '716',
    name: 'Zimbabwe',
    i18n: {
      en: 'Zimbabwe',
      es: 'Zimbabue',
    },
    region: 'Africa',
    phoneCode: '263',
    currency: 'ZWL',
    locale: 'bwg-ZW',
    flagEmoji: '🇿🇼',
  },
];

export const countryCodes = COUNTRY_MASTER_DATA.map((country) => country.code);
